### PR TITLE
Ws-query

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Raster Tile Stream nach Python](https://trello.com/c/xvDYHdi1/1193-raster-tile-stream-nach-python)

**Comment by jdroenner** [comment]
i get a notification:

> /git/geoengine-python/env/lib/python3.10/site-packages/rasterio/windows.py:314: RasterioDeprecationWarning: The height, width, and precision parameters are unused, deprecated, and will be removed in 2.0.0.

is this a general issue in xarray or something we need to address?

**Comment by ChristianBeilschmidt** [comment]
> i get a notification:
> 
> > /git/geoengine-python/env/lib/python3.10/site-packages/rasterio/windows.py:314: RasterioDeprecationWarning: The height, width, and precision parameters are unused, deprecated, and will be removed in 2.0.0.
> 
> is this a general issue in xarray or something we need to address?

[bb57bad](https://github.com/geo-engine/geoengine-python/pull/108/commits/bb57badb81abc9b990bd10c7a45e444ce084cc8e)

**Review by jdroenner — DISMISSED** [review]

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Pull request merged**
